"""Tests for MusicBrainz PostgreSQL schema definitions."""

from groovemap_schema.postgres import _MUSICBRAINZ_INDEXES, _MUSICBRAINZ_TABLES


def test_musicbrainz_tables_defined():
    table_names = [name for name, _ in _MUSICBRAINZ_TABLES]
    assert "musicbrainz schema" in table_names
    assert "musicbrainz.artists table" in table_names
    assert "musicbrainz.labels table" in table_names
    assert "musicbrainz.releases table" in table_names
    assert "musicbrainz.relationships table" in table_names
    assert "musicbrainz.external_links table" in table_names


def test_musicbrainz_tables_use_if_not_exists():
    # ALTER migrations (e.g. widening columns to BIGINT) cannot use IF NOT EXISTS;
    # only CREATE TABLE statements must be idempotent via IF NOT EXISTS.
    for name, sql in _MUSICBRAINZ_TABLES:
        if "CREATE TABLE" in sql:
            assert "IF NOT EXISTS" in sql, f"{name} missing IF NOT EXISTS"


def test_musicbrainz_discogs_id_columns_are_bigint():
    # Discogs IDs are i64 from the extractor and now exceed int4 range (2.1B);
    # cross-reference columns must be BIGINT to avoid "integer out of range".
    expected = {
        "musicbrainz.artists table": "discogs_artist_id BIGINT",
        "musicbrainz.labels table": "discogs_label_id BIGINT",
        "musicbrainz.releases table": "discogs_release_id BIGINT",
        "musicbrainz.release_groups table": "discogs_master_id BIGINT",
    }
    found = dict.fromkeys(expected, False)
    for name, sql in _MUSICBRAINZ_TABLES:
        if name in expected:
            assert expected[name] in sql, f"{name} missing {expected[name]}"
            found[name] = True
    assert all(found.values()), f"missing tables: {[n for n, ok in found.items() if not ok]}"


def test_musicbrainz_has_bigint_widening_migrations():
    # Existing databases need explicit ALTER COLUMN ... TYPE BIGINT; CREATE TABLE
    # IF NOT EXISTS is a no-op on tables that already exist as INTEGER.
    migrations = [sql for name, sql in _MUSICBRAINZ_TABLES if "ALTER COLUMN" in sql]
    assert any("musicbrainz.artists ALTER COLUMN discogs_artist_id TYPE BIGINT" in m for m in migrations)
    assert any("musicbrainz.labels ALTER COLUMN discogs_label_id TYPE BIGINT" in m for m in migrations)
    assert any("musicbrainz.releases ALTER COLUMN discogs_release_id TYPE BIGINT" in m for m in migrations)
    assert any("musicbrainz.release_groups ALTER COLUMN discogs_master_id TYPE BIGINT" in m for m in migrations)


def test_musicbrainz_indexes_defined():
    index_names = [name for name, _ in _MUSICBRAINZ_INDEXES]
    assert "idx_mb_artists_discogs_id" in index_names
    assert "idx_mb_labels_discogs_id" in index_names
    assert "idx_mb_releases_discogs_id" in index_names
    assert "idx_mb_rels_source" in index_names
    assert "idx_mb_links_mbid" in index_names
    assert "idx_mb_rels_updated_at" in index_names
    assert "idx_mb_links_updated_at" in index_names


def test_musicbrainz_indexes_use_if_not_exists():
    for name, sql in _MUSICBRAINZ_INDEXES:
        assert "IF NOT EXISTS" in sql, f"{name} missing IF NOT EXISTS"


def test_relationships_has_unique_constraint():
    # The natural key must include begin_date/end_date/attributes
    # so that two relationship instances differing only in date range (e.g. a
    # re-joined band membership) or attributes (e.g. a multi-instrument performer
    # credit) do not collapse into a single row via ON CONFLICT DO UPDATE.
    for name, sql in _MUSICBRAINZ_TABLES:
        if name == "musicbrainz.relationships table":
            assert "CONSTRAINT relationships_natural_key UNIQUE NULLS NOT DISTINCT" in sql
            assert "source_mbid, target_mbid, source_entity_type, target_entity_type," in sql
            assert "relationship_type, begin_date, end_date, attributes" in sql


def test_external_links_has_unique_constraint():
    for name, sql in _MUSICBRAINZ_TABLES:
        if name == "musicbrainz.external_links table":
            assert "UNIQUE (mbid, entity_type, service_name, url)" in sql


def test_relationships_natural_key_migration_present():
    # Existing databases carry the old, narrower autogenerated
    # constraint — CREATE TABLE IF NOT EXISTS is a no-op for them, so an explicit
    # migration must locate and replace it.
    migrations = [sql for name, sql in _MUSICBRAINZ_TABLES if "widen natural key" in name]
    assert len(migrations) == 1
    migration_sql = migrations[0]
    assert "DROP CONSTRAINT" in migration_sql
    assert "ADD CONSTRAINT relationships_natural_key" in migration_sql
    assert "UNIQUE NULLS NOT DISTINCT" in migration_sql


def test_relationships_and_external_links_gain_updated_at_column():
    # Unlike every other MusicBrainz entity table, `relationships` and
    # `external_links` were declared with `created_at` only. `musicbrainz-sql-loader`
    # needs `updated_at` as its delete-reconciliation key, spelled exactly like the
    # loader's own interim startup ALTER so that ALTER is a no-op once this ships.
    # CREATE TABLE IF NOT EXISTS is a no-op against an existing table, so the
    # column is added through an explicit, idempotent ALTER.
    expected = {
        "musicbrainz.relationships.updated_at column": "ALTER TABLE musicbrainz.relationships ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()",
        "musicbrainz.external_links.updated_at column": "ALTER TABLE musicbrainz.external_links ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()",
    }
    found = dict.fromkeys(expected, False)
    for name, sql in _MUSICBRAINZ_TABLES:
        if name in expected:
            assert sql == expected[name], f"{name} does not match the expected statement"
            found[name] = True
    assert all(found.values()), f"missing migrations: {[n for n, ok in found.items() if not ok]}"


def test_relationships_and_external_links_updated_at_are_indexed():
    # The loader's reconciliation scan filters on `updated_at < run start`, the
    # same access path the Discogs entity tables already index.
    index_sql = dict(_MUSICBRAINZ_INDEXES)
    assert index_sql["idx_mb_rels_updated_at"] == "CREATE INDEX IF NOT EXISTS idx_mb_rels_updated_at ON musicbrainz.relationships (updated_at)"
    assert index_sql["idx_mb_links_updated_at"] == "CREATE INDEX IF NOT EXISTS idx_mb_links_updated_at ON musicbrainz.external_links (updated_at)"


class TestWideningGuard:
    """The BIGINT widening has to stay a no-op in every state it can meet.

    `_execute_schema_statements` logs a failed statement and carries on, so a
    single transient ALTER failure leaves an install whose column is still
    narrow while the run goes on to create the graph views that read it. From
    that point an unguarded ALTER raises `cannot alter type of a column used by
    a view or rule` forever. The guard has to notice the dependency and skip.
    """

    def _guards(self) -> dict[str, str]:
        return {name: sql for name, sql in _MUSICBRAINZ_TABLES if name.endswith("widen to BIGINT")}

    def test_every_provider_id_column_has_a_guarded_widening(self) -> None:
        assert set(self._guards()) == {
            "musicbrainz.artists.discogs_artist_id widen to BIGINT",
            "musicbrainz.labels.discogs_label_id widen to BIGINT",
            "musicbrainz.releases.discogs_release_id widen to BIGINT",
            "musicbrainz.release_groups.discogs_master_id widen to BIGINT",
        }

    def test_the_guard_skips_a_column_that_is_already_wide(self) -> None:
        for name, sql in self._guards().items():
            assert "current_type = 'bigint'" in sql, f"{name} does not gate on the column type"

    def test_the_guard_consults_the_rewrite_rule_dependencies(self) -> None:
        # A view reads a column through its _RETURN rewrite rule, and pg_depend
        # records that rule's dependency on the exact attribute. Anything less
        # specific (the table, or no check at all) is what the reviewer
        # reproduced as a hard failure.
        for name, sql in self._guards().items():
            assert "pg_depend" in sql, f"{name} does not consult pg_depend"
            assert "pg_rewrite" in sql, f"{name} does not consult pg_rewrite"
            assert "dependency.refobjsubid" in sql, f"{name} does not narrow the dependency to one column"
            assert "relkind IN ('v', 'm')" in sql, f"{name} does not restrict the dependents to views"

    def test_the_guard_notices_and_returns_instead_of_altering(self) -> None:
        for name, sql in self._guards().items():
            assert "RAISE NOTICE" in sql, f"{name} fails silently instead of saying why it skipped"
            notice_at = sql.index("RAISE NOTICE")
            alter_at = sql.index("ALTER TABLE")
            assert notice_at < alter_at, f"{name} reaches the ALTER before the dependency check"
            # The NOTICE arm has to leave the block, not fall through to the ALTER.
            assert "RETURN;" in sql[notice_at:alter_at], f"{name} does not return after the notice"

    def test_the_guard_names_the_column_and_its_dependents_in_the_notice(self) -> None:
        sql = self._guards()["musicbrainz.labels.discogs_label_id widen to BIGINT"]
        assert "skipping widen of musicbrainz.labels.discogs_label_id" in sql
        notice = sql[sql.index("RAISE NOTICE") : sql.index("current_type, dependent_views")]
        # Two placeholders, two arguments: the type it is stuck at and what holds it there.
        assert notice.count("%") == 2

    def test_the_guard_still_widens_when_nothing_depends_on_the_column(self) -> None:
        for name, sql in self._guards().items():
            table, column = name.removeprefix("musicbrainz.").removesuffix(" widen to BIGINT").split(".")
            assert f"ALTER TABLE musicbrainz.{table} ALTER COLUMN {column} TYPE BIGINT" in sql
