name: Publish image

on:
  push:
    tags: ["v*"]

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  publish:
    uses: groovemap-music/.github/.github/workflows/reusable-image-release.yml@c5bf723cad17fa10c0b758a005d6565f47f04f36
    with:
      image-name: database-schema
      requires-private-library: true
      prepare-command: just prepare-runtime-wheel
    secrets: inherit
